=== ScilifelabDataCentre/data.scilifelab.se/schemas/data/services.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "/schemas/data/services.schema.json",
    "title": "Services Schema",
    "description": "Schema for validating service objects used in the data.scilifelab.se",
    "type": "array",
    "items": {
      "type": "object",
      "required": [
        "owner",
        "type",
        "search_tags",
        "name",
        "description",
        "url",
        "maintained_by"
      ],
      "properties": {
        "owner": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "SciLifeLab Data Centre",
              "NBIS",
              "SciLifeLab Affiliated",
              "SciLifeLab Infrastructure"
            ]
          },
          "minItems": 1,
          "uniqueItems": true,
          "description": "responsible for the service."
        },
        "type": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1,
          "uniqueItems": true,
          "description": "One or more categories describing the type of service."
        },
        "search_tags": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1,
          "uniqueItems": true,
          "description": "Search keywords associated with the service."
        },
        "weight": {
           "type": "integer",
            "minimum": 0,
            "description": "OPTIONAL: Position on the services page. Lower numbers are shown first; services without a weight are listed alphabetically after weighted ones."
        },
        "name": {
          "type": "string",
          "minLength": 1,
          "description": "Title or name of the service."
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "description": "Short description about the service."
        },
        "thumbnail": {
          "type": "string",
          "description": "OPTIONAL: Path to a thumbnail image for the service.",
          "pattern": "^\\/img\\/service_thumbnails\\/[^\\s]+\\.(jpg|jpeg|png|svg)$"
        },
        "thumbnail_border": {
          "type": "boolean",
          "description": "OPTIONAL: Whether to display a border around the thumbnail image.",
          "default": false
        },
        "url": {
          "type": "string",
          "description": "URL linking to the service.",
          "pattern": "^(https?:\\/\\/|\\/|mailto:).+"
        },
        "maintained_by": {
          "type": "string",
          "minLength": 1,
          "description": "Name of the individual or organization that maintains the service."
        },
        "maintained_by_url": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Web address of the maintaining organization or individual."
        },
        "support_email": {
          "type": "string",
          "format": "email",
          "description": "OPTIONAL: Email address to contact for support regarding the service."
        },
        "support_website": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Website URL for service support or documentation."
        },
        "support_github": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: GitHub repository URL for the service."
        },
        "support_status": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Status page URL for the service."
        },
        "support_slack": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Slack channel or workspace URL for service support."
        },
        "support_impact": {
          "type": "string",
          "format": "uri",
          "description": "OPTIONAL: Link to dashboard showing impact of the service."
        },
        "data_source_type": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "uniqueItems": true,
          "description": "OPTIONAL: Type of data source associated with the service."
        },
        "ddls": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "uniqueItems": true,
          "description": "OPTIONAL: Scientific area of the services that are also data sources."
        },
        "disease_type": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "uniqueItems": true,
          "description": "OPTIONAL: Disease types associated with the services that are also data sources."
        }
      },
      "additionalProperties": false
    }
}

=== ScilifelabDataCentre/data.scilifelab.se/data/services.json
[
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "Swedish Research Institute Affiliation"
    ],
    "search_tags": [
      "SciLifeLab Serve",
      "AI",
      "Serve",
      "Artificial intelligence",
      "Apps",
      "DASH",
      "R-Shiny",
      "Hosting",
      "Data sharing",
      "Machine learning",
      "SciLifeLab",
      "Data Centre"
    ],
    "name": "SciLifeLab Serve",
    "weight": 1,
    "description": "SciLifeLab Serve is a platform offering machine learning model serving, data science app hosting (Shiny, Gradio, Streamlit, Dash, etc.).",
    "url": "https://serve.scilifelab.se/",
    "maintained_by": "SciLifeLab Data Centre",
    "thumbnail": "/img/service_thumbnails/Serve.png",
    "thumbnail_border": true,
    "maintained_by_url": "https://scilifelab.se/data",
    "support_email": "serve@scilifelab.se",
    "support_website": "https://serve.scilifelab.se/docs/",
    "support_status": "https://status.dc.scilifelab.se/795925203",
    "support_impact": "https://service-dashboard.dc.scilifelab.se/public-dashboards/8bcddb335945451ba3d1fb8232dd9d9b"
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "Everyone"
    ],
    "search_tags": [
      "Pathogens portal",
      "infectious disease data",
      "Swedish Pathogens Portal",
      "Pandemic preparedness portal",
      "COVID-19",
      "SciLifeLab",
      "Data Centre",
      "Tool"
    ],
    "name": "Swedish Pathogens Portal",
    "weight": 1,
    "description": "Facilitates the sharing and promotion of pandemic preparedness and infectious disease data",
    "thumbnail": "/img/service_thumbnails/pathogens.png",
    "thumbnail_border": true,
    "url": "https://pathogens.se/",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://scilifelab.se/data",
    "support_email": "pathogens@scilifelab.se",
    "support_github": "https://github.com/ScilifelabDataCentre/pathogens-portal/tree/develop",
    "support_status": "https://status.dc.scilifelab.se/793602036",
    "data_source_type": [
      "Data source"
    ]
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "Swedish Research Institute Affiliation"
    ],
    "search_tags": [
      "Data submission",
      "Data repository",
      "SciLifeLab",
      "Data Centre",
      "Tool",
      "Figshare",
      "SciLifeLab Data Repository",
      "Data Repository"
    ],
    "name": "SciLifeLab Data Repository",
    "weight": 1,
    "description": "Repository for publishing any kind of research-related data, posters, presentations, and more!",
    "thumbnail": "/img/service_thumbnails/figshare.jpg",
    "url": "https://scilifelab.figshare.com/",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "figshare@scilifelab.se",
    "support_website": "https://www.scilifelab.se/data-ai/repository",
    "support_impact": "https://service-dashboard.dc.scilifelab.se/public-dashboards/6b18d7f79f23464bb510e8dc06be6e6a",
    "data_source_type": [
      "Repository"
    ],
    "ddls": [
      "Epidemiology and Biology of Infection",
      "Cell and Molecular Biology",
      "Evolution and Biodiversity",
      "Precision Medicine and Diagnostics"
    ],
    "disease_type": [ 
      "General"
    ]
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "SciLifeLab Affiliation"
    ],
    "search_tags": [
      "SciLifeLab Atlassian Services",
      "Atlassian",
      "Jira",
      "Confluence",
      "Trello",
      "Collaboration tool"
    ],
    "name": "SciLifeLab Atlassian Services",
    "thumbnail": "/img/service_thumbnails/Atlassian_services.png",
    "thumbnail_border": true,
    "description": "Access to Jira, Confluence, and Trello is available for those affiliated with SciLifeLab.",
    "url": "https://scilifelab.atlassian.net/",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "datacentre@scilifelab.se",
    "support_impact": "https://service-dashboard.dc.scilifelab.se/public-dashboards/de33e302931f40c3aa115e0a38549034"
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "SciLifeLab Operations"
    ],
    "search_tags": [
      "SciLifeLab Typeform",
      "survey",
      "surveys",
      "user feedback"
    ],
    "name": "SciLifeLab Typeform",
    "thumbnail": "/img/service_thumbnails/Typeform.png",
    "thumbnail_border": true,
    "url": "mailto:datacentre@scilifelab.se?subject=Request%20access%20to%20SciLifeLab%20Typeform",
    "description": "Contact Data Centre to create dynamic forms with Typeform.",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "datacentre@scilifelab.se"
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "SciLifeLab Affiliation"
    ],
    "search_tags": [
      "Publications",
      "Publications database",
      "Infrastructure publications database",
      "articles",
      "infrastructure",
      "reporting"
    ],
    "name": "SciLifeLab Infrastructure Publications Database",
    "description": "Databases showing publications involving SciLifeLab infrastructure units.",
    "url": "https://publications.scilifelab.se",
    "thumbnail_border": true,
    "thumbnail": "/img/service_thumbnails/Publications.png",
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "datacentre@scilifelab.se",
    "support_status": "https://status.dc.scilifelab.se/793602112",
    "support_impact": "https://service-dashboard.dc.scilifelab.se/public-dashboards/50c100ee5635434bae7f9315fa80235d"
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "SciLifeLab Affiliation"
    ],
    "search_tags": [
      "Slack",
      "coworking",
      "collaboration",
      "communication"
    ],
    "name": "SciLifeLab Slack",
    "description": "Access to Slack to enable collaboration and communication.",
    "maintained_by": "SciLifeLab Data Centre",
    "thumbnail": "/img/service_thumbnails/Slack.png",
    "thumbnail_border": true,
    "url": "https://scilifelab.slack.com/",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "datacentre@scilifelab.se",
    "support_impact": "https://service-dashboard.dc.scilifelab.se/public-dashboards/93ae57afd935431e8d06f1a8049ad93b"
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "SciLifeLab Affiliation"
    ],
    "search_tags": [
      "Filesharing",
      "file sharing",
      "collaboration",
      "SUNET drive"
    ],
    "name": "SciLifeLab SUNET drive",
    "thumbnail": "/img/service_thumbnails/SUNET_Drive.png",
    "thumbnail_border": true,
    "description": "A cloud-based file sharing and storage service.",
    "maintained_by": "SciLifeLab Data Centre",
    "url": "https://scilifelab.drive.sunet.se/",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "datacentre@scilifelab.se",
    "support_impact": "https://service-dashboard.dc.scilifelab.se/public-dashboards/d4402d5a18c847a39f48d4ee45c898f3"
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "SciLifeLab Affiliation"
    ],
    "search_tags": [
      "Publications",
      "Publications database",
      "affiliates publications database",
      "articles",
      "affiliates",
      "reporting"
    ],
    "name": "SciLifeLab Affiliates Publications Database",
    "description": "Databases showing publications from research fellows affiliated with SciLifeLab.",
    "url": "https://publications-affiliated.scilifelab.se",
    "thumbnail_border": true,
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "datacentre@scilifelab.se",
    "thumbnail": "/img/service_thumbnails/Publications.png",
    "support_status": "https://status.dc.scilifelab.se/793602106",
    "support_impact": "https://service-dashboard.dc.scilifelab.se/public-dashboards/50c100ee5635434bae7f9315fa80235d"
  },
  {
    "owner": [
      "SciLifeLab Data Centre"
    ],
    "type": [
      "SciLifeLab Affiliation"
    ],
    "search_tags": [
      "Protocols",
      "Versioning",
      "reproducibility",
      "Data sharing",
      "Data management",
      "Tool",
      "SciLifeLab",
      "Data Centre",
      "SciLifeLab Protocols"
    ],
    "name": "SciLifeLab Protocols",
    "description": "Licences are provided for those affiliated with SciLifeLab to use protocols.io - used for the creation, sharing, and versioning of laboratory and computational protocols.",
    "thumbnail": "/img/service_thumbnails/Protocols.png",
    "url": "https://www.scilifelab.se/data-ai/protocols/",
    "thumbnail_border": true,
    "maintained_by": "SciLifeLab Data Centre",
    "maintained_by_url": "https://www.scilifelab.se/data-ai/",
    "support_email": "datacentre@scilifelab.se"
  },
  {
    "owner": [
      "SciLifeLab Affiliated"
    ],
    "type": [
      "Everyone"
    ],
    "search_tags": [ 
      "GeneSPIDER tutorial",
      "Gene regulatory network inference",
      "Benchmarking tools",
      "MATLAB",
      "Git",
      "Bitbucket",
      "Simulation",
      "Experiment design",
      "Installation guide",
      "Tool",
      "SciLifeLab",
      "Data Centre"
    ],
    "name": "GeneSPIDER version: v2",
    "description": "GeneSPIDER(v2) is a Matlab toolbox for gene regulatory network inference and benchmarking with controlled network and data properties.",
    "thumbnail": "/img/service_thumbnails/GeneSPIDER.png",
    "thumbnail_border": true,
    "url": "https://sonnhammer-tutorials.bitbucket.io/genespider.html#Getting_started",
    "maintained_by": "Sonnhammer Group",
